kind: pipeline
name: default
workspace:
  base: /tmp
  path: "."
steps:
- name: build
  image: node:latest
  commands:
  - npm install
- name: test
  image: node:8.11.4-alpinet
  commands:
  - npm run test
